contact_links:
  - name: Flarum Forum Discussion
    about: Please check the discussion on the Flarum forum for more information and context about this extension. It might help you understand if your issue has already been discussed or resolved.
    url: https://discuss.flarum.org/d/34569-pallet-theme-new
